server:
  port: 7005

spring:
  application:
    name: restaurant-service

  data:
    mongodb:
      username: restaurant
      password: restaurant_pass
      database: restaurantService
      port: 27019
      host: localhost
      authentication-database: admin
