spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      generate-ddl: true
      ddl-auto: create
      database: POSTGRESQL
      open-in-view: false
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
