spring:
  cloud:
    config:
      allow-override: true
      override-none: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0

security:
  oauth2:
    resource:
      jwt:
        key-value: springSigningKey