server:
  port: 7002

spring:
  application:
    name: meal-service

  datasource:
    url: jdbc:postgresql://postgresql-meal:5432/mealService
    username: meal
    password: meal_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      ddl-auto: create
      database: POSTGRESQL
      open-in-view: false
      show-sql: true

axon:
  axonserver:
    servers: axonserver:8124
  eventhandling:
    processors:
      meal-group:
        mode: subscribing