server:
  port: 7004

spring:
  application:
    name: payment-service

  data:
    mongodb:
      username: payment
      password: payment_pass
      database: paymentService
      port: 27017
      host: mongodb-payment
      authentication-database: admin

axon:
  axonserver:
    servers: axonserver:8124
  eventhandling:
    processors:
      payment-group:
      mode: subscribing
