server:
  port: 7006

spring:
  application:
    name: meal-service

  data:
    mongodb:
      username: user
      password: user_pass
      database: userService
      port: 27017
      host: localhost
      authentication-database: admin

axon:
  eventhandling:
    processors:
      user-group:
        mode: subscribing