server:
  port: 7002

spring:
  application:
    name: meal-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mealService
    username: meal
    password: meal_pass
    driver-class-name: org.postgresql.Driver
