server:
  port: 7006

spring:
  application:
    name: user-service

  data:
    mongodb:
      username: user
      password: user_pass
      database: userService
      host: localhost
      port: 27018

security:
  oauth2:
    client:
      client-id: springClient
      client-secret: springSecret
      signing-key: springSigningKey
      token-validity-seconds: 300
      refresh-token-validity-seconds: 1500