server:
  port: 7005

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantService
    username: restaurant
    password: restaurant_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      ddl-auto: create
      database: POSTGRESQL
      open-in-view: false
      show-sql: true