spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:9090/inventory_hub
    username: postgres
    password: ${DBPASSWORD}
    driver-class-name: org.postgresql.Driver
