server:
  port: 7003

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5435/orderService
    username: order_user
    password: order
    driver-class-name: org.postgresql.Driver
