server:
  port: 7002

spring:
  application:
    name: meal-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mealService
    username: meal_user
    password: meal
    driver-class-name: org.postgresql.Driver
