server:
  port: 7002

spring:
  application:
    name: meal-service

  data:
    mongodb:
      username: user
      password: user_pass
      database: userService
      port: 27018
      host: mongodb-user
      authentication-database: admin

axon:
  axonserver:
    servers: axonserver:8124
  eventhandling:
    processors:
      user-group:
        mode: subscribing