server:
  port: 7004

spring:
  application:
    name: payment-service

  data:
    mongodb:
      username: payment
      password: payment_pass
      database: payementService
      port: 27020
      host: localhost
      authentication-database: admin