server:
  port: 7003

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgresql-order:5432/orderService
    username: order
    password: order_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      ddl-auto: create
      database: POSTGRESQL
      open-in-view: false
      show-sql: true

axon:
  axonserver:
    servers: axonserver:8124
  eventhandling:
    processors:
      order-group:
        mode: subscribing