server:
  port: 7004

spring:
  application:
    name: payment-service

  data:
    mongodb:
      username: payment
      password: payment_pass
      database: paymentService
      port: 27020
      host: mongodb-payment
      authentication-database: admin

axon:
  eventhandling:
    processors:
      payment-group:
        mode: subscribing
  axonserver:
    servers: axonserver:8124
