spring:
  application:
    name: meal-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mealService
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
