server:
  port: 7001

spring:
  application:
    name: address-service

  data:
    mongodb:
      url: mongodb://localhost:27017/addressService
      username: root
      database: addressService

rapidapi-mapencoding:
  url: https://google-maps-geocoding.p.rapidapi.com/geocode/json
  rapidApiHost: google-maps-geocoding.p.rapidapi.com
  rapidApiKey: f4e9ad6671msh6a82f138256beafp10c4a1jsna68bf7508a5a

axon:
  eventhandling:
    processors:
      address-group:
        mode: subscribing
